---
name: 'webmanifestconfig'
---
SilverStripe\Control\Director:
  rules:
    "site.webmanifest": Kraftausdruck\Webmanifest\Webmanifest

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Kraftausdruck\Webmanifest\Extensions\WebmanifestSiteConfigExtension

Kraftausdruck\Webmanifest\Webmanifest:
  tab: 'Root.Webmanifest'
  fields:
    name: 'SiteConfig.Title'
    short_name: 'SiteConfig'
    description: 'SiteConfig.Tagline'
    start_url: '/home'
    background_color: '#fff'
    icons:
      - src: '/android-chrome-192x192.png'
        sizes: '192x192'
        type: 'image/png'
      - src: '/android-chrome-384x384.png'
        sizes: '384x384'
        type: 'image/png'
---
Only:
  moduleexists: 'cms'
---
Page:
  extensions:
    - Kraftausdruck\Webmanifest\Extensions\WebmanifestPageExtension
