---
name: "webmanifestconfig"
---
SilverStripe\Control\Director:
  rules:
    "site.webmanifest": Kraftausdruck\Webmanifest\Webmanifest

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Kraftausdruck\Webmanifest\Extensions\WebmanifestSiteConfigExtension

Kraftausdruck\Webmanifest\Webmanifest:
  tab: "Root.Webmanifest"
  fields:
    name: "SiteConfig.Title" # max. 30 charactes
    short_name: "SiteConfig" # max. 12 charactes
    description: "SiteConfig.Tagline" # max. 132 charactes
    start_url: "/"
    background_color: "#ffffff"
    theme_color: "#ffffff"
    icons:
      - src: "/icon-192.png"
        sizes: "192x192"
        type: "image/png"
      - src: "/icon-512.png"
        sizes: "512x512"
        type: "image/png"
---
Only:
  moduleexists: "cms"
---
Page:
  extensions:
    - Kraftausdruck\Webmanifest\Extensions\WebmanifestPageExtension
